### ISSUE TITLE
Timeout and Cancelled errors

### ISSUE THREAD

**Issue by guillemc23** [Krukov/cashews#150]
Hello!

I'm developing a map based application using [DeckGL](https://deck.gl/). I am providing a tile layer using [Titiler](https://github.com/developmentseed/titiler) which is based on [FastAPI](https://fastapi.tiangolo.com/lo/). I am managing very big files so I have implemented a cache using Cashews with Redis to store the computed tiles. It does work extremely well most of the time.

But sometimes, when I move the map or zoom in quicky, my application it starts generating a lot of requests and cancelling others (for example, when the tile is out of the viewport). This causes my application to start throwing `TimeoutErrors` and `CancelledErrors` when trying to connect to Redis like the ones below.

Why do you think this behavior appears? Is there any configuration or parameter to control this situation?

Thanks in advance! 

```
2023-05-23 13:50:59 During handling of the above exception, another exception occurred:
2023-05-23 13:50:59 
2023-05-23 13:50:59 Traceback (most recent call last):
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/cashews/backends/redis/client.py", line 26, in execute_command
2023-05-23 13:50:59     return await super().execute_command(command, *args, **kwargs)
2023-05-23 13:50:59            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/client.py", line 509, in execute_command
2023-05-23 13:50:59     conn = self.connection or await pool.get_connection(command_name, **options)
2023-05-23 13:50:59                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 1607, in get_connection
2023-05-23 13:50:59     await connection.connect()
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 609, in connect
2023-05-23 13:50:59     raise TimeoutError("Timeout connecting to server")
2023-05-23 13:50:59 redis.exceptions.TimeoutError: Timeout connecting to server
2023-05-23 13:50:59 redis: can not execute command: SET
2023-05-23 13:50:59 Traceback (most recent call last):
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 640, in _connect
2023-05-23 13:50:59     reader, writer = await asyncio.open_connection(
2023-05-23 13:50:59                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/streams.py", line 48, in open_connection
2023-05-23 13:50:59     transport, _ = await loop.create_connection(
2023-05-23 13:50:59                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/base_events.py", line 1034, in create_connection
2023-05-23 13:50:59     infos = await self._ensure_resolved(
2023-05-23 13:50:59             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/base_events.py", line 1405, in _ensure_resolved
2023-05-23 13:50:59     return await loop.getaddrinfo(host, port, family=family, type=type,
2023-05-23 13:50:59            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/base_events.py", line 864, in getaddrinfo
2023-05-23 13:50:59     return await self.run_in_executor(
2023-05-23 13:50:59            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59 asyncio.exceptions.CancelledError
2023-05-23 13:50:59 
2023-05-23 13:50:59 During handling of the above exception, another exception occurred:
2023-05-23 13:50:59 
2023-05-23 13:50:59 Traceback (most recent call last):
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 603, in connect
2023-05-23 13:50:59     await self.retry.call_with_retry(
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
2023-05-23 13:50:59     return await do()
2023-05-23 13:50:59            ^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 639, in _connect
2023-05-23 13:50:59     async with async_timeout.timeout(self.socket_connect_timeout):
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/async_timeout/__init__.py", line 129, in __aexit__
2023-05-23 13:50:59     self._do_exit(exc_type)
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/async_timeout/__init__.py", line 212, in _do_exit
2023-05-23 13:50:59     raise asyncio.TimeoutError
2023-05-23 13:50:59 TimeoutError
2023-05-23 13:50:59 
2023-05-23 13:50:59 During handling of the above exception, another exception occurred:
2023-05-23 13:50:59 
2023-05-23 13:50:59 Traceback (most recent call last):
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/cashews/backends/redis/client.py", line 26, in execute_command
2023-05-23 13:50:59     return await super().execute_command(command, *args, **kwargs)
2023-05-23 13:50:59            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/client.py", line 509, in execute_command
2023-05-23 13:50:59     conn = self.connection or await pool.get_connection(command_name, **options)
2023-05-23 13:50:59                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 1607, in get_connection
2023-05-23 13:50:59     await connection.connect()
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/site-packages/redis/asyncio/connection.py", line 609, in connect
2023-05-23 13:50:59     raise TimeoutError("Timeout connecting to server")
2023-05-23 13:50:59 redis.exceptions.TimeoutError: Timeout connecting to server
```

**Comment by Krukov** [comment]
Hi @guillemc23 

1) cashews by default just skip cashing if redis-py throws any connection related error and only logging it. You can disable this log by logger configuration ( https://docs.python.org/3/library/logging.config.html - ask me if you need example)  or you can tell cashews do not ignore this errors by setup `cache.setup("redis://....", suppress=False)`
2) yep as @AIGeneratedUsername  you can try to increase timeouts  
```python
cache.setup("redis://..../", socket_timeout=10, retry_on_timeout=True, wait_for_connection_timeout=10)
# defaults :
#     wait_for_connection_timeout = 10 
#     retry_on_timeout = False
#     socket_timeout = 1
```
3) You can increase  number of max_connections  ( it is 10 by default)
```python
cache.setup("redis://..../",  max_connections=100)
```
4) Check you network or DNS because traceback tell us that we cant resolve redis host name ( get ip address ) . Where are your redis is hosted?   
```
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/base_events.py", line 1034, in create_connection
2023-05-23 13:50:59     infos = await self._ensure_resolved(
2023-05-23 13:50:59             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23 13:50:59   File "/opt/bitnami/python/lib/python3.11/asyncio/base_events.py", line 1405, in _ensure_resolved
2023-05-23 13:50:59     return await loop.getaddrinfo(host, port, family=family, type=type,
2023-05-23 13:50:59            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by guillemc23** [comment]
Hello @Krukov, I will test your configuration and report back.
My Redis is running locally from a docker container, and the app trying to access it is also running locally on another docker container. I'm quite certain that the app has access to Redis since it does retrieve tiles from the cache really fast when I try to access one single cached file.

**Comment by Krukov** [comment]
@guillemc23  Do you have any updates ? Can I close the issue ?

**Comment by guillemc23** [comment]
I tested what you proposed, but without luck. I ended up writing a debouncer to reduce the amount of petitions of tiles so this error happens way less frequently. It still happens when the requests pile up, but I don't think it's related to this library, but to redis-py. I posted there with no response.

Thanks for your help!
