### ISSUE TITLE
ValueError: Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by viktorfreiman** [Krukov/cashews#200]
When running uvicorn with string args create_metrics_middleware failes. But if you change app to a callable function it works

``uvicorn.error : You must pass the application as an import string to enable 'reload' or 'workers'.``

~~~py
import uvicorn
from cashews.contrib.prometheus import create_metrics_middleware

metrics_middleware = create_metrics_middleware()
uvicorn.run("demo:app_not_defined")

~~~

gives error
~~~sh
vscode ➜ /workspaces/project (master) $ python3 demo.py 
Traceback (most recent call last):
  File "/workspaces/popins-v3/demo.py", line 5, in <module>
    uvicorn.run("demo:app_not_defined")
  File "/home/vscode/.local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/vscode/.local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/vscode/.local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/home/vscode/.local/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/popins-v3/demo.py", line 4, in <module>
    metrics_middleware = create_metrics_middleware()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/cashews/contrib/prometheus.py", line 12, in create_metrics_middleware
    _DEFAULT_METRIC = Histogram(
                      ^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/prometheus_client/metrics.py", line 579, in __init__
    super().__init__(
  File "/home/vscode/.local/lib/python3.11/site-packages/prometheus_client/metrics.py", line 155, in __init__
    registry.register(self)
  File "/home/vscode/.local/lib/python3.11/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'cashews_operations_latency_seconds_sum', 'cashews_operations_latency_seconds_bucket', 'cashews_operations_latency_seconds', 'cashews_operations_latency_seconds_created', 'cashews_operations_latency_seconds_count'}
~~~

**Comment by Krukov** [comment]
Thanks for reporting. Kinda expected problem )) , I will fix it soon

**Comment by Krukov** [comment]
Should be fine with 7.0.2
