### ISSUE TITLE
'cache.incr' and 'cache.keys_match' API commands examples from documentation do not work

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#23]
Copy/pasted from the documentation:
```python
import asyncio
from cashews import cache

cache.setup("mem://")  # configure as in-memory cache

async def func():
    await cache.set(key="key", value={"any": True}, expire=60, exist=None)  # -> bool
    await cache.get("key")  # -> Any
    await cache.get_many("key1", "key2")
    await cache.incr("key") # -> int
    await cache.delete("key")
    await cache.delete_match("pattern:*")
    await cache.keys_match("pattern:*") # -> List[str]
    await cache.expire("key", timeout=10)
    await cache.get_expire("key")  # -> int seconds to expire
    await cache.ping(message=None)  # -> bytes
    await cache.clear()
    await cache.is_locked("key", wait=60)  # -> bool
    async with cache.lock("key", expire=10):
       ...
    await cache.set_lock("key", value="value", expire=60)  # -> bool
    await cache.unlock("key", "value")  # -> bool


asyncio.run(func())
```
Run result:
```
Traceback (most recent call last):
  File "/local.py", line 46, in <module>
    asyncio.run(func())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/local.py", line 31, in func
    await cache.incr("key") # -> int
  File "/venv/lib/python3.10/site-packages/cashews/validation.py", line 63, in _invalidate_middleware
    return await call(*args, key=key, **kwargs)
  File "/venv/lib/python3.10/site-packages/cashews/wrapper.py", line 45, in _auto_init
    return await call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/cashews/disable_control.py", line 12, in _is_disable_middleware
    return await call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/cashews/backends/memory.py", line 75, in incr
    value = int(self._get(key, 0)) + 1
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

Process finished with exit code 1
```
If comment out `await cache.incr("key") # -> int` to skip the problematic command:
```
Traceback (most recent call last):
  File "/_local.py", line 46, in <module>
    asyncio.run(func())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/_local.py", line 34, in func
    await cache.keys_match("pattern:*") # -> List[str]
  File "/venv/lib/python3.10/site-packages/cashews/validation.py", line 62, in _invalidate_middleware
    return await call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/cashews/wrapper.py", line 45, in _auto_init
    return await call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/cashews/disable_control.py", line 12, in _is_disable_middleware
    return await call(*args, **kwargs)
TypeError: object async_generator can't be used in 'await' expression

Process finished with exit code 1
```

I do not know how to fix `await cache.keys_match("pattern:*")` because `[key async for key in cache.keys_match("pattern:*")` does not work too.

**Comment by AIGeneratedUsername** [comment]
The example in the documentation
```python
    await cache.incr("key") # -> int
```
can be fixed by `await cache.set(key="key", value=99, expire=60, exist=None)  # -> bool`

Could you please explain what is wrong with the  `await cache.keys_match("pattern:*")` example in your documentation?

**Comment by Krukov** [comment]
Yep `incr` not working because previously key was set not as an integer.

`cache.keys_match` - that is my fault, it is working with a raw backend. There is something wrong with middleware approach

**Comment by Krukov** [comment]
A made a [PR](https://github.com/Krukov/cashews/pull/27/files) , so if you like you can review it. 

Just want to remind you not use `keys_match` with redis in production

**Comment by AIGeneratedUsername** [comment]
Thanks for the fix. If this issue will be automatically closed after merging, then I leave it as is.
