### ISSUE TITLE
UnSecureDataError when reading JSON value

### ISSUE THREAD

**Issue by rkrell** [Krukov/cashews#50]
Affects version: 3.3.0

I have the following key defining a stringified JSON as value stored in Redis:
```
$ redis-cli -h localhost -p 16379
localhost:16379> get packing:product_scan_220000000111
"{\"shipping_information_id\": 1, \"scanned_product\": {\"id\": 43, \"barcode\": \"220000000111\", \"dimensions\": [334, 36]}, \"added_products\": [], \"packing_auto\": true}"
localhost:16379> 
```

Using this code:

```python
from cashews import cache

...
cache.setup(f"redis://{cfg.redis.host}:{cfg.redis.port}/0",
            password=redis_password,
            prefix="packing")

result = await cache.get("packing:product_scan_220000000111")
```

I get a `UnSecureDataError`:

```
Traceback (most recent call last):
  File "/home/automation/lib/python3.7/site-packages/aiorun.py", line 212, in new_coro
    await coro
  File "/home/automation/packing/application.py", line 136, in main
    ":product_scan_220000000111")
  File "/homeautomation/packing/application.py", line 39, in cache_logging_middleware
    return await call(*args, **kwargs)
  File "/homeautomation/lib/python3.7/site-packages/cashews/validation.py", line 63, in _invalidate_middleware
    return await call(*args, key=key, **kwargs)
  File "/home/automation/lib/python3.7/site-packages/cashews/wrapper.py", line 50, in _auto_init
    return await call(*args, **kwargs)
  File "/home/automation/lib/python3.7/site-packages/cashews/disable_control.py", line 12, in _is_disable_middleware
    return await call(*args, **kwargs)
  File "/home/automation/lib/python3.7/site-packages/cashews/serialize.py", line 35, in get
    return await self._get_value(await super().get(key), key, default=default)
  File "/home/automation/lib/python3.7/site-packages/cashews/serialize.py", line 39, in _get_value
    return self._process_value(value, key, default=default)
  File "/home/automation/lib/python3.7/site-packages/cashews/serialize.py", line 59, in _process_value
    raise UnSecureDataError()
cashews.serialize.UnSecureDataError
```

It the serializer parses the value and splits it on '_' for some check, but I completely miss the background for this.

Is this expected?
How can I read this value properly in _cashews_?

**Comment by AIGeneratedUsername** [comment]
Maybe all signature checks must be skipped if a user did not provide a `hash_key`.

**Comment by rkrell** [comment]
What is the background here with this hash key? I couldn't find any hint in the documentation.
If it is necessary, how should I use it? Why is the value split on '_' chars, is this a standard?

The point here is that the key is provided to Redis by a different system not using cashews.

**Comment by rkrell** [comment]
I found the basic meaning in serializer.py, but isn't that a proprietary approach to add a prefix separated by '_' to the user's value?

**Comment by AIGeneratedUsername** [comment]
Are you trying to use 'cashews' instead of 'aioredis' directly only to have a Pickle serializer to pickle/unpickle your data when working with Redis? Just trying to understand your use case when you already have some data set without 'cashews', but then you get this data back with 'cashews' and not with 'aioredis' directly. 

I know this is not an answer to your question, but in my own project I use 'aioredis' directly with my own serializer:
```python
class PickleSerializer(_Base):
    @staticmethod
    async def loads(value: bytes | None, key: AnyKeyT, *, default: Any = None) -> Any:
        if value is None:
            return None
        if value == default:
            return default
        if value.isdigit():
            return int(value)
        with suppress(zlib.error):  # The error indicates that the value is shorter than `compress_min_size_bytes`.
            value = zlib.decompress(value)
        unpickled = pickle.loads(value, fix_imports=False, encoding="bytes")
        try:
            repr(unpickled)  # https://github.com/Krukov/cashews/issues/26#issuecomment-1030613323
        except AttributeError:
            await super().delete(key)  # type: ignore[misc]
            return default
        return unpickled

    @staticmethod
    def dumps(value: Any) -> bytes:
        compress_min_size_bytes = 100  # Compression smaller objects may give either the same or even larger size.
        dumped = pickle.dumps(value, protocol=pickle.HIGHEST_PROTOCOL, fix_imports=False)
        return zlib.compress(dumped) if sys.getsizeof(dumped) > compress_min_size_bytes else dumped
```

**Comment by rkrell** [comment]
> Are you trying to use 'cashews' instead of 'aioredis' directly only to have a Pickle serializer to pickle/unpickle your data when working with Redis? Just trying to understand your use case when you already have some data set without 'cashews', but then you get this data back with 'cashews' and not with 'aioredis' directly.
> 
> ...

The data are written by a completely different system to Redis. redis is used for inter-process communication between these two systems. It cannot be expected the "foreign" system adds a hash key as expected by cashews.

To simulate the problem I just use cashews as shown in the simple example.

Generally, cashews should not have any "opinion" about the value itself by default.
The value I use is a valid value for Redis.

**Comment by rkrell** [comment]
Just to show how the Redis message is created by a non-cashews system:

```python
        redis_message = SomePydanticObjectBasedOnBaseModel(
             ...
        )
        redis_key = '{}:product_scan_{}'.format(
            "packing",
            shipping_information_id)
        redis_expiration = timedelta(days=7)

        redis_client.setex(redis_key, redis_expiration,
                           redis_message.json())
```

The project uses redis==3.5.3.

**Comment by rkrell** [comment]
Nevertheless, if _cashews_ is actually mentioned not to be used for interoperation between different implementations due to a special pickling/unpickling it's easy to use plain _aioredis_ for my purpose.

Pydantic's [BaseModel.parse_raw](https://pydantic-docs.helpmanual.io/usage/exporting_models/#custom-json-deserialisation) does the job here and establishes an object from the encoded JSON without any custom unpickler.

**Comment by Krukov** [comment]
@rkrell 

With a shame I can say that it is possible to get value without any serialization. I did very silly mistake with naming (english is not native for me, I don't know how it can happened)  - `set_row` , `get_row`. It should be `raw` of course

```python
await cache.get_row("test")
```
 
 So I going to fix this naming without backward compatibility ( for versions 4.x.x)

**Comment by rkrell** [comment]
Oh, great, haven't even noticed that possibility :-)
The community may forgive you the breaking change ;-)
